name: Deploy to github pages

on:
  push:
    branches:
      - master
      - gh-readonly-queue/master/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: delaguardo/setup-clojure@12.5
        with:
          bb: latest
      - run: bb quickblog render
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public/
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
